backend:
  name: github
  repo: cassiorsfreitas/blog
  base_url: https://cassiorsfreitas.com
  auth_endpoint: api/auth
media_folder: "public/images"
public_folder: "/images"
publish_mode: editorial_workflow
display_url: https://cassiorsfreitas.com
slug:
  encoding: 'ascii'
  clean_accents: true
collections:
  - name: posts
    label: posts
    folder: posts
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss'
        }
      - { label: 'Post Image', name: 'image', widget: 'image', required: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }

      - { label: 'Body', name: 'body', widget: 'markdown' }
